package uk.gov.hmcts.jui.sscs.scenario

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import uk.gov.hmcts.jui.sscs.scenario.utils._

object JUIDecision {
  val MinThinkTime = Environment.minThinkTime
  val MaxThinkTime = Environment.maxThinkTime
  val CommonSSCSHeader = Environment.commonSSCSHeader

  val submitDecision = exec(http("TC012_JUI_SelectCase_MakeDecision")
    .get("/api/decisions/state/SSCS/Benefit/${P_case}/create"))
    .pause(7)
    .exec(http("TC013_JUI_SelectCase_MakeDecision_SelectPreliminaryView")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/create")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","visitedPages":{"create":true,"final-decision":true}},"event":"continue"}"""))
      .resources(http("TC014_JUI_SelectCase_MakeDecision_GET_SelectAwards")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/preliminary-advanced")))
    .pause(MinThinkTime, MaxThinkTime)

    .exec(http("TC015_JUI_SelectCase_MakeDecision_POST_SelectAwards")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/preliminary-advanced")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true}},"event":"continue"}"""))
      .resources(http("TC016_JUI_SelectCase_MakeDecision_GET_set_award_dates")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/set-award-dates")))
    .pause(MinThinkTime, MaxThinkTime)

    .exec(http("TC017_JUI_SelectCase_MakeDecision_POST_set_award_dates")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/set-award-dates")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true}},"event":"continue"}"""))
      .resources(http("TC018_JUI_SelectCase_MakeDecision_GET_scores")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/scores")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC019_JUI_SelectCase_MakeDecision_POST_scores")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/scores")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true}},"event":"continue"}"""))
      .resources(http("TC020_JUI_SelectCase_MakeDecision_GET_preparing_food")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/preparing-food")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC021_JUI_SelectCase_MakeDecision_POST_preparing_food")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/preparing-food")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"dailyLivingPreparingFood":"4","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true,"preparing-food":true}},"event":"continue"}"""))
      .resources(http("TC022_JUI_SelectCase_MakeDecision_GET_taking_nutrition")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/taking-nutrition")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC023_JUI_SelectCase_MakeDecision_POST_taking_nutrition")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/taking-nutrition")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"dailyLivingPreparingFood":"4","dailyLivingTakingNutrition":"6","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true,"preparing-food":true,"taking-nutrition":true}},"event":"continue"}"""))
      .resources(http("TC024_JUI_SelectCase_MakeDecision_GET_washing_bathing")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/washing-bathing")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC025_JUI_SelectCase_MakeDecision_POST_washing_bathing")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/washing-bathing")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"dailyLivingPreparingFood":"4","dailyLivingTakingNutrition":"6","dailyLivingWashingBathing":"3","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true,"preparing-food":true,"taking-nutrition":true,"washing-bathing":true}},"event":"continue"}"""))
      .resources(http("TC026_JUI_SelectCase_MakeDecision_GET_reading_signs")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/reading-signs")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC027_JUI_SelectCase_MakeDecision_POST_reading_signs")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/reading-signs")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"dailyLivingPreparingFood":"4","dailyLivingTakingNutrition":"6","dailyLivingWashingBathing":"3","dailyLivingReadingSigns":"4","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true,"preparing-food":true,"taking-nutrition":true,"washing-bathing":true,"reading-signs":true}},"event":"continue"}"""))
      .resources(http("TC028_JUI_SelectCase_MakeDecision_GET_budgeting_decisions")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/budgeting-decisions")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC029_JUI_SelectCase_MakeDecision_POST_budgeting_decisions")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/budgeting-decisions")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"dailyLivingPreparingFood":"4","dailyLivingTakingNutrition":"6","dailyLivingWashingBathing":"3","dailyLivingReadingSigns":"4","dailyLivingMakingBudgetDecisions":"2","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true,"preparing-food":true,"taking-nutrition":true,"washing-bathing":true,"reading-signs":true,"budgeting-decisions":true}},"event":"continue"}"""))
      .resources(http("TC030_JUI_SelectCase_MakeDecision_GET_planning_journeys")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/planning-journeys")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC031_JUI_SelectCase_MakeDecision_POST_planning_journeys")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/planning-journeys")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"dailyLivingPreparingFood":"4","dailyLivingTakingNutrition":"6","dailyLivingWashingBathing":"3","dailyLivingReadingSigns":"4","dailyLivingMakingBudgetDecisions":"2","MobilityPlanningJourneys":"4","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true,"preparing-food":true,"taking-nutrition":true,"washing-bathing":true,"reading-signs":true,"budgeting-decisions":true,"planning-journeys":true}},"event":"continue"}"""))
      .resources(http("TC032_JUI_SelectCase_MakeDecision_GET_movingaround")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/moving-around")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC033_JUI_SelectCase_MakeDecision_POST_movingaround")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/moving-around")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"dailyLivingPreparingFood":"4","dailyLivingTakingNutrition":"6","dailyLivingWashingBathing":"3","dailyLivingReadingSigns":"4","dailyLivingMakingBudgetDecisions":"2","MobilityPlanningJourneys":"4","MobilityMovingAround":"8","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true,"preparing-food":true,"taking-nutrition":true,"washing-bathing":true,"reading-signs":true,"budgeting-decisions":true,"planning-journeys":true,"moving-around":true}},"event":"continue"}"""))
      .resources(http("TC034_JUI_SelectCase_MakeDecision_GET_check")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/check"),
        http("TC034_JUI_SelectCase_MakeDecision_GET_check_light-tabular-851b10ccdd-v1.woff2")
          .get("/assets/fonts/light-tabular-851b10ccdd-v1.woff2"),
        http("TC034_JUI_SelectCase_MakeDecision_GET_check_bold-tabular-b89238d840-v1.woff2")
          .get("/assets/fonts/bold-tabular-b89238d840-v1.woff2")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC035_JUI_SelectCase_MakeDecision_POST_check")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/check")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true,"preparing-food":true,"taking-nutrition":true,"washing-bathing":true,"reading-signs":true,"budgeting-decisions":true,"planning-journeys":true,"moving-around":true},"forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","decisionNotes":"test of removal from list","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"dailyLivingPreparingFood":"4","dailyLivingTakingNutrition":"6","dailyLivingWashingBathing":"3","dailyLivingReadingSigns":"4","dailyLivingMakingBudgetDecisions":"2","MobilityPlanningJourneys":"4","MobilityMovingAround":"8","reasonsTribunalView":"Performance Testing 12345678910"},"event":"continue"}"""))
      .resources(http("TC036_JUI_SelectCase_MakeDecision_GET_check_tribunal")
        .get("/api/decisions/state/SSCS/Benefit/${P_case}/check-tribunal")))
    .pause(MinThinkTime, MaxThinkTime)
    .exec(http("TC037_JUI_SelectCase_MakeDecision_POST_check_tribunal")
      .post("/api/decisions/state/SSCS/Benefit/${P_case}/check-tribunal")
      .headers(CommonSSCSHeader)
      .body(StringBody("""{"formValues":{"preliminaryView":"yes","visitedPages":{"create":true,"preliminary-advanced":true,"final-decision":true,"set-award-dates":true,"scores":true,"preparing-food":true,"taking-nutrition":true,"washing-bathing":true,"reading-signs":true,"budgeting-decisions":true,"planning-journeys":true,"moving-around":true},"forDailyLiving":"standardRate","forMobility":"standardRate","compareToDWPAward":"Higher","decisionNotes":"test of removal from list","awardStartDateDay":"12","awardStartDateMonth":"04","awardStartDateYear":"2018","endDateRadio":"endDate","awardEndDateDay":"12","awardEndDateMonth":"03","awardEndDateYear":"2019","preparingFood":true,"takingNutrition":true,"managingTherapy":false,"washingBathing":true,"managingToilet":false,"dressingUndressing":false,"communicatingVerbally":false,"readingAndUnderstanding":true,"engagingWithOtherPeople":false,"makingBudgetingDecisions":true,"planningFollowingJourneys":true,"movingAround":true,"dailyLivingPreparingFood":"4","dailyLivingTakingNutrition":"6","dailyLivingWashingBathing":"3","dailyLivingReadingSigns":"4","dailyLivingMakingBudgetDecisions":"2","MobilityPlanningJourneys":"4","MobilityMovingAround":"8","reasonsTribunalView":"Performance Testing 12345678910"},"event":"continue"}""")))
    .pause(MinThinkTime, MaxThinkTime)
}
